name: shutterbox-container-image-app
region: eu-west-1
s3BucketPrefix: shutterbox-nested
stacks:
  - name: container-java-root
    template: templates/main.yml
    capabilities:
      - CAPABILITY_NAMED_IAM