AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack for ECS Java ShutterBox App with S3, Auto Scaling, ALB, Code Deploy

Parameters:
  ECRImage:
    Type: String
    Description: Full ECR image URI

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://shutterbox-cf-templates.s3.eu-west-1.amazonaws.com/templates/vpc.yml
      Parameters:
        AppName: image-app

  ECSAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://shutterbox-cf-templates.s3.eu-west-1.amazonaws.com/templates/ecs-cluster-alb-fargate.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        ECRImage: !Ref ECRImage

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECSAppStack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: https://shutterbox-cf-templates.s3.eu-west-1.amazonaws.com/templates/ecs-codedeploy.yml
      Parameters:
        ClusterName: !GetAtt ECSAppStack.Outputs.ClusterName
        ServiceName: !GetAtt ECSAppStack.Outputs.ServiceName
        TargetGroup1: !GetAtt ECSAppStack.Outputs.TargetGroup1Name
        TargetGroup2: !GetAtt ECSAppStack.Outputs.TargetGroup2Name
        ListenerArn: !GetAtt ECSAppStack.Outputs.ListenerArn

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS to access app
    Value: !GetAtt ECSAppStack.Outputs.LoadBalancerDNS

  S3BucketName:
    Description: S3 bucket used by the app
    Value: !GetAtt ECSAppStack.Outputs.S3BucketName