AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack for ECS Java App with S3, Auto Scaling, ALB

Parameters:
  ECRImage:
    Type: String
    Description: Full ECR image URI

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}/templates/vpc.yml
      Parameters:
        AppName: image-app

  ECSAppStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${S3Bucket}/templates/ecs-cluster-alb-fargate.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        ECRImage: !Ref ECRImage

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS to access app
    Value: !GetAtt ECSAppStack.Outputs.LoadBalancerDNS

  S3BucketName:
    Description: S3 bucket used by the app
    Value: !GetAtt ECSAppStack.Outputs.S3BucketName