name: Deploy ECS App with Nested Stacks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package CloudFormation templates
        run: |
          aws cloudformation package \
            --template-file image-app-infrastructure/templates/main.yml \
            --s3-bucket ${{ secrets.CFN_BUCKET }} \
            --output-template-file packaged.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file packaged.yml \
            --stack-name shutterbox-container-root \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides ECRImage=${{ secrets.ECR_IMAGE_URI }}