name: Upload and Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
          aws-region: eu-west-1

      - name: Upload templates to S3
        run: |
          aws s3 cp templates/ s3://shutterbox-cf-templates/templates/ --recursive --region eu-west-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name shutterbox-ecs-app \
            --template-file templates/main.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              ECRImage=${{ secrets.ECR_IMAGE_URI }} \
            --region eu-west-1