name: Deploy ECS App with Nested Stacks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
          aws-region: eu-west-1

      - name: Run GitSync via Docker
        run: |
          docker run --rm \
            -v "$PWD:/app" \
            -v "$HOME/.aws:/root/.aws" \
            -w /app \
            public.ecr.aws/aws-cloudformation/git-sync:latest \
            deploy --config image-app-infrastructure/gitsync-config.yml

      - name: Deploy CloudFormation using GitSync
        run: |
          gitsync deploy --config image-app-infrastructure/gitsync-config.yml