name: Deploy ECS App with Nested Stacks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
          aws-region: eu-west-1

      - name: Install GitSync CLI from GitHub Release
        run: |
          GITSYNC_VERSION=0.1.17
          curl -L -o gitsync https://github.com/awslabs/git-sync/releases/download/v${GITSYNC_VERSION}/gitsync-linux-amd64
          chmod +x gitsync
          sudo mv gitsync /usr/local/bin/gitsync

      - name: Verify GitSync version
        run: gitsync --version

      - name: Deploy CloudFormation using GitSync
        run: |
          gitsync deploy --config image-app-infrastructure/gitsync-config.yml
