name: Deploy ECS App with GitSync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
          aws-region: eu-west-1

      - name: Install GitSync CLI
        run: |
          curl -sSL https://gitsync.io/install.sh | bash

      - name: Deploy CloudFormation using GitSync
        run: |
          gitsync deploy --config templates/gitsync-config.yml